##########
# "A Shaky Truce"
# Starkville Civil Rights Struggles, 1960-1980
# https://github.com/ShakyTruce/ShakyTruce
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
url: https://ShakyTruce.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
baseurl: /ShakyTruce
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: A Shaky Truce
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Civil Rights Struggles in Starkville, Mississippi, 1960-1980
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: This digital oral and public history project was a cooperative effort between faculty and students at Mississippi State University History Department and Libraries. The site narrates the unique history of Starkville, Mississippi’s civil rights struggles with particular emphasis on the local fight for school desegregation. African Americans fought for equal rights and freedom on the streets and in the schools of every Southern town during the Jim Crow Era. Yet each community and its residents have their own stories to tell about how local individuals organized, protested against inequality, and fought for equal employment, school desegregation, and voting rights. Through the use of digitized archival documents and oral history interviews, “A Shaky Truce” highlights Starkville’s story and the voices of its participants in order to position this town and its people as critical reflections of this national movement.
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: ShakyTruce

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: collectionbuilder-shakytruce-metadata 

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
